name: ci
on: [push]

jobs:
  test:
    name: using go ${{ matrix.go }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Lint & Test
        run: make setup-ci ci
